# GENERATED FILE: edits made by hand will not be preserved.
---
# Source: edge-stack/templates/aes-ratelimit.yaml
apiVersion: getambassador.io/v2
kind: RateLimitService
metadata:
  name: edge-stack-ratelimit
  namespace: default
  labels:
    product: aes
spec:
  service: 127.0.0.1:8500
---
# Source: edge-stack/templates/aes-authservice.yaml
apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: edge-stack-auth
  namespace: default
  labels:
    product: aes
spec:
  proto: grpc
  auth_service: 127.0.0.1:8500
  allow_request_body: false
  status_on_error:
    code: 504
---
# Source: edge-stack/templates/aes-internal.yaml
# Configure DevPortal
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  # This Mapping name is referenced by convention, it's important to leave as-is.
  name: edge-stack-devportal
  namespace: default
  labels:
    product: aes
spec:
  prefix: /documentation/
  rewrite: /docs/
  service: 127.0.0.1:8500
---
# Source: edge-stack/templates/aes-internal.yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: edge-stack-devportal-assets
  namespace: default
  labels:
    product: aes
spec:
  prefix: /documentation/(assets|styles)/(.*)(.css)
  prefix_regex: true
  regex_rewrite:
    pattern: /documentation/(.*)
    substitution: /docs/\1
  service: 127.0.0.1:8500
  add_response_headers:
    cache-control:
      value: public, max-age=3600, immutable
      append: false
---
# Source: edge-stack/templates/aes-internal.yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  # This Mapping name is what the demo uses. Sigh.
  name: edge-stack-devportal-demo
  namespace: default
  labels:
    product: aes
spec:
  prefix: /docs/
  rewrite: /docs/
  service: 127.0.0.1:8500
---
# Source: edge-stack/templates/aes-internal.yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  # This Mapping name is referenced by convention, it's important to leave as-is.
  name: edge-stack-devportal-api
  namespace: default
  labels:
    product: aes
spec:
  prefix: /openapi/
  rewrite: ''
  service: 127.0.0.1:8500
