{{- define "ambassador.apiext.labels" -}}
product: aes
app.kubernetes.io/name: {{ include "ambassador.name" . }}-apiext
app.kubernetes.io/part-of: {{ .Release.Name }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- if ne .Values.deploymentTool "getambassador.io" }}
helm.sh/chart: {{ include "ambassador.chart" . }}
{{- if .Values.deploymentTool }}
app.kubernetes.io/managed-by: {{ .Values.deploymentTool }}
{{- else }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
{{- end }}
{{- end }}

{{- if .Values.apiext.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ambassador.rbacName" . }}-aes-apiext
  labels:
    {{- include "ambassador.apiext.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "list", "watch" ]
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    resourceNames:
      - filterpolicies.getambassador.io
      - filters.getambassador.io
      - ratelimits.getambassador.io
    verbs: [ "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ambassador.rbacName" . }}-aes-apiext
  labels:
    {{- include "ambassador.apiext.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ambassador.rbacName" . }}-aes-apiext
subjects:
  - name: {{ include "ambassador.fullname" . }}-apiext
    namespace: {{ include "ambassador.namespace" . }}
    kind: ServiceAccount
{{- end }}
