---
# Source: edge-stack/charts/emissary-ingress/crds/filter.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app.kubernetes.io/name: ambassador
    product: aes
  name: filters.getambassador.io
spec:
  group: getambassador.io
  names:
    categories:
    - ambassador-crds
    kind: Filter
    plural: filters
    shortNames:
    - fil
    singular: filter
  scope: Namespaced
  versions:
  - name: v1beta2
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        description: Filter specifies an Ambassador Edge Stack filter
        type: object
        x-kubernetes-preserve-unknown-fields: true
  - name: v2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: Filter specifies an Ambassador Edge Stack filter
        type: object
        x-kubernetes-preserve-unknown-fields: true
