---
# Source: edge-stack/charts/edge-stack/crds/filterpolicy.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app.kubernetes.io/name: ambassador
    product: aes
  name: filterpolicies.getambassador.io
spec:
  group: getambassador.io
  names:
    categories:
    - ambassador-crds
    kind: FilterPolicy
    plural: filterpolicies
    shortNames:
    - fp
    singular: filterpolicy
  scope: Namespaced
  versions:
  - name: v1beta2
    schema:
      openAPIV3Schema:
        description: Filter specifies an Ambassador Edge Stack filter
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: false
    storage: false
  - name: v2
    schema:
      openAPIV3Schema:
        description: Filter specifies an Ambassador Edge Stack filter
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: false
    storage: false
  - name: v3alpha1
    schema:
      openAPIV3Schema:
        description: Filter specifies an Ambassador Edge Stack filter
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
