emissary-ingress:
  deploymentTool: getambassador.io
  replicaCount: 1
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              product: aes
          topologyKey: kubernetes.io/hostname
        weight: 100
  env:
    POLL_EVERY_SECS: '60'
    AMBASSADOR_URL: 'https://ambassador.ambassador.svc.cluster.local'
    AMBASSADOR_INTERNAL_URL: 'https://127.0.0.1:8443'
    AMBASSADOR_DRAIN_TIME: '600'
  podAnnotations:
    consul.hashicorp.com/connect-inject: 'false'
    sidecar.istio.io/inject: 'false'
  containerNameOverride: aes
  restartPolicy: Always
  terminationGracePeriodSeconds: "0"
  service:
    type: LoadBalancer
    # TODO(lukeshu): It's silly that we need to set this, but the OSS
    # Helm chart breaks if you set deploymentTool="getambassador.io"
    # without setting service.selector.  We should fix that, but until
    # then, just explicitly set this to what would be (if not for
    # deploymentTool) the default value.
    selector:
      app.kubernetes.io/name: edge-stack
      app.kubernetes.io/instance: edge-stack
  deploymentNameOverride: aes

enableTestService: true

deploymentTool: getambassador.io
redis:
  serviceSelector:
    service: ambassador-redis
