emissary-ingress:
  replicaCount: 1
  createNamespace: true
  deploymentTool: getambassador.io
  env:
    POLL_EVERY_SECS: '60'
    AMBASSADOR_URL: 'https://ambassador.ambassador.svc.cluster.local'
    AMBASSADOR_INTERNAL_URL: 'https://127.0.0.1:8443'
    AMBASSADOR_DRAIN_TIME: '600'
  podAnnotations:
    consul.hashicorp.com/connect-inject: 'false'
    sidecar.istio.io/inject: 'false'
  containerNameOverride: aes
  restartPolicy: Always
  terminationGracePeriodSeconds: "0"
  service:
    type: LoadBalancer

    # Note that target http ports need to match your ambassador configurations service_port
    # https://www.getambassador.io/reference/modules/#the-ambassador-module
    selector:
      service: ambassador
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              service: ambassador
          topologyKey: kubernetes.io/hostname
        weight: 100

registry:
  create: true
devportal:
  docsPrefix: "/docs/"
rateLimit:
  deploymentExtraName: edge-stack-ratelimit
authService:
  deploymentExtraName: edge-stack-auth
  optional_configurations:
    allow_request_body: false
    status_on_error:
      code: 504
redis:
  serviceSelector:
    service: ambassador-redis
deploymentTool: getambassador.io
